### ISSUE TITLE
Fails to download it. I downloaded it manually and configured but have memory issue now.

### ISSUE THREAD

**Issue by jais-nikhil** [bigpaulie/yii2-social-share#11]
Hi There,

I was trying to install it using composer but it keeps failing. I installed manually but now it says memory error when I try to use it. Kindly help.

"Out of memory (allocated 4194304) (tried to allocate 8791506277656 bytes)"

C:\wamp\www\ecommerce>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing bower-asset/font-awesome (v4.7.0): Downloading (100%)
  - Installing bower-asset/bootstrap-social (4.12.0): Downloading (100%)
  - Installing bigpaulie/yii2-social-share (dev-master 49a0855): Cloning 49a0855616
    Failed to download bigpaulie/yii2-social-share from source: Failed to clone https://github.com/bigpaulie/yii2-social
-share.git, git was not found, check that it is installed and in your PATH env.

'git' is not recognized as an internal or external command,
operable program or batch file.

    Now trying to download from dist
  - Installing bigpaulie/yii2-social-share (dev-master 49a0855): Downloading (100%)
Writing lock file

**Comment by bigpaulie** [comment]
Hello there @jais-nikhil , as you can see in the error message "git was not found, check that it is installed and in your PATH env." git is either not installed or on your system system path.

Please install and properly configure your system, afterwards your problem will go away.
