### ISSUE TITLE
Working with callbacks

### ISSUE THREAD

**Issue by ak868308** [bigpaulie/yii2-social-share#7]
Hello
This is a awesome library for social media share. I found this one much faster than others. 
Thanks for the same.
Here I want to know something more. Can you please know me how to work with callbacks using this package? Is there any callback method?
I want to store or process tha data on successfull share

Here is the example what actually I need.
https://github.com/innubu/social-share-callback
Sometime I want to navigate the user to another page or call some actions.
Thanks

**Comment by bigpaulie** [comment]
Hello @ak868308 ,
Theoretically it should be possible by binding onto the "unload" event.
However this may not always work ... 
I can't promise you that I will add this feature, the idea behind this library is to be as simple as possible. But still I will look into it.

https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunload

Thank you for your interest in my library.
